---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории.
- Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.

non-functional:
- Сайт должен быть способен обрабатывать большое количество трафика.
- Сайт должен быть протестирован на совместимость с последними версиями браузеров.
- Сайт должен быть безопасным и защищать данные пользователя.
- Сайт должен иметь мобильную версию.
- Сайт должен быть способен обрабатывать большое количество трафика.
- Сайт должен быть доступен на различных устройствах.
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.

implicit: 
- необходима регистрация и указание конатных данных для офрлмения заказа
- Поля формы регистрации должны заполняться корректо
- Пользователь должен иметь возможность выбрать вид доставки 
- Пользователь должен иметь возможность выбора формы оплаты 
- Сайт должен быть итегрироваван с системами платежей. 
- сайт должен иметь инструменты маркетинга. Скидки,купоны,рекомендации.
- Сайт должен позволять вести учет количества товаров.
- Пользователь должен иметь возможность редактировать количесво товаров в корзине 
- В карточке товара должно быть поле для коментриев и отзывов
- Должн абыть система рейтингов и оценок
- Возможность интеграции видео в карточку товара на ряду с фото
- Чат с администрацией магазина
- При переключении языка переводится весь конент, кроме названия брендов.
- У пользователя должен быть личный кабинет со статистикой 
- Сайт должен иметь систему рассылок и оповещий 
