functional: 
  - Интернет-магазинапо продаже товаров должен иметь каталог со списком товаров 1
  - Должна быть возможность перехода на следующую и предыдущую страницу каталога 2
  - Должна быть возможность фильтрации и поиска товара 3
  - Должна быть возможность перехода в карточку товара 4
  - Должна быть возможность перехода в форму регистрации нового пользователя 5  
  - Должна быть возможность перехода в форму авторизации пользователя 6
  - Должна быть возможность перехода в корзину 7
  - Должна быть возможность перехода в список заказов только для авторизованного пользователя 8
  - Должна быть возможность выбора русского или английского языка отображения текста 9
  - Пользователь может просматривать полный список товаров в каталоге 10
  - Пользователь может фильтровать товар и просматривать отфильтрованный товар в каталоге 11
  - Пользователь может искать товары по ключевому слову 12
  - Пользователь может выбирать определенную категорию товара из выпадающего списка 13
  - Пользователь может выбирать все категории товара одновременно с  помощью соответствующего значения в выпадающем списке 14
  - В зависимости от выбранной категории должна быть фильтрация товара по бренду 15
  - Независимо от выбранной категории должна быть фильтрация товара по цене, цвету, размеру и наличию 16
  - Пользователь может одновременно искать товары по поисковой строке и включать фильтрацию 17
  - В миниатюре товара отображается название, описание, рейтинг, цена со скидкой и без скидки 18
  - Пользователь может вернуться обратно в каталог из корзины или списка заказов или карточки товара 19
  - Отображается название товара, его рейтинг, цена со скидкой и цена без скидки 20
  - Пользователь может добавить товар в корзину в нужном количестве 21
  - Пользователь может перейти в отфильтрованный каталог для просмотра других товаров аналогичной категории 22 
  - Пользователь может изменить количество товара или удалить товар из корзины 23
  - Пользователь может авторизоваться и посмотреть заказ 25
  - Пользователь может авторизоваться и оформить заказ с переходом на страницу оплаты 26
non-functional: 
  - Должна быть разработана веб-версия сайта в виде SPA без перезагрузки страницы 27
  - Должна быть разработана мобильная версия сайта 28
  - Сайт должен иметь адаптивную верстку при просмотре веб-страницы на компьютерах и на мобильных устройствах 29
  - В подвале сайта должна быть предусмотрена кнопка для перехода на мобильную версию сайта и обратно 30
  - Размеры кнопок, расположение элементов в формах и дизайн должны сохраняться при переключении  языка текста с русского на английский 31
  - Сайт должен содержать шапку с основным меню, тело с меню фильтрации и поиска, подвал c кнопкой перехода в режим просмотра веб версии и мобильной версии 32
  - Веб-версия и мобильная версия сайта должны быть выполнены в едином стиле 33
implicit: 
  - При отсутствии соединения с сетью интернет должно отображаться стандартное текстовое сообщение браузера об отсутствии подключения 34
  - Протокол передачи данных HTTP должен поддерживать расширения шифрования SSL TLS 35
  - Должен быть реализован механизм управления сессиями Cookies 36
  - В сессии браузера должна храниться информация о корзине, сделанных заказах и данные учетной записи пользователя 37
  - Поиск товаров должен быть нечувствителен к регистру символов 38
  - Поля авторизации, регистрации и выбора цены товара в каталоге должны валидировать данные, вводимые пользователем 39
